package com.example.battleshipbackendspring.model;


import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Id;

/**
 * This class persists in MongoDB
 */

@Data
@NoArgsConstructor
public class PlayerMatches {

    /**
     *   The socket id is autogenerated by MongoDB.
     */

    @Id
    String webSocketAddress;

    /**
     * user id of player1
     */
    private String player1;

    /**
     * user id of player2
     */
    private String player2;


    /**
     * The socket id is autogenerated by MongoDB.
     *
     * @param player1
     * @param player2
     */
    public PlayerMatches(String player1, String player2) {
        this.player1 = player1;
        this.player2 = player2;
    }


    /**
     * A constructor that only populates the socket id and the user id of player one. The model is instantiated
     * initially from this constructor
     * @param player1
     */
    public PlayerMatches(String player1) {
        this.player1 = player1;
    }


}
